#!/usr/bin/env bash

# usage: ./create_sprite_sheet [run,jump] 5
#
# description: 
# Create sprite sheet with 5 columns for run1.png, run2.png, jump1, jump2, etc.

names=$(echo $1 | sed 's/,/\n/')
files=""

for name in $names; do
  size=$(file $name[0]*1.png | awk -F, '{ print $2 }')
  files+="($name)|"
done
files=${files::-1}

files=$(ls | egrep $files)

montage $files -background transparent -tile $2 -geometry "$size" out.png

